### ISSUE TITLE
kafka starting as a root user

### ISSUE THREAD

**Issue by baboune** [puppet-community/puppet-kafka#17]
Hi,

When the script to run kafka launches, kafka is ran as root.  This is not recommended.  Better to run kafka as a "kafka" process.

**Comment by dhoppe** [comment]
Hello, 

thank you very much for your contribution. This issue has been resolved by commit https://github.com/puppet-community/puppet-kafka/commit/389fd55d0e75b23e00aa4915babfb74a4bc5508a.

Kind regards,
Dennis
