### ISSUE TITLE
Ubuntu 12.04/14.04 LTS Compatibility Broken

### ISSUE THREAD

**Issue by SinisterMinister** [puppet-community/puppet-kafka#24]
Commit 6bd3c8fb5dc12a64aa4a26ef918ed8665206f1e3 changed the `init.d` script to use `runuser` instead of `exec sudo`. `runuser` isn't available on those versions which prevents Kafka from starting.

**Comment by geoah** [comment]
+1 Just bumped on this on 14.04. Is there a quick fix/hack that I we can do for this?

**Comment by SinisterMinister** [comment]
We worked around it by forking the module for now and doing the fix manually.

**Comment by dhoppe** [comment]
Hello Codey, 

thank you very much for your contribution. This issue has been resolved by commit https://github.com/puppet-community/puppet-kafka/commit/389fd55d0e75b23e00aa4915babfb74a4bc5508a.

Kind regards,
Dennis
