### ISSUE TITLE
Puppetforge module outdated: The init script leaves pidfile if there's an error when starting

### ISSUE THREAD

**Issue by ersiko** [puppet-community/puppet-kafka#26]
If there's any error when starting kafka, the pidfile will stay, and you won't be able to start kafka until you delete it manually.

Tested in ubuntu. I'll provide info about other distros.

**Comment by dhoppe** [comment]
Hello Tomàs, 

thank you very much for your contribution. This issue has been resolved by commit https://github.com/puppet-community/puppet-kafka/commit/389fd55d0e75b23e00aa4915babfb74a4bc5508a.

Kind regards,
Dennis
