### ISSUE TITLE
Puppet forge module outdated: ArgumentError: Could not find declared class java 

### ISSUE THREAD

**Issue by ersiko** [puppet-community/puppet-kafka#27]
Looks like a requirement is missing. This module is trying to use the "java" class but it doesn't exist. Maybe requirement for https://forge.puppetlabs.com/puppetlabs/java should be added?

**Comment by ersiko** [comment]
I tried to add the dependency and find out it's already added in this repo, but it's not in puppet forge. Maybe it would be nice to update the module there?

**Comment by dhoppe** [comment]
Hello Tomàs, 

thank you very much for your contribution. This issue has been resolved by commit https://github.com/puppet-community/puppet-kafka/commit/389fd55d0e75b23e00aa4915babfb74a4bc5508a.

Kind regards,
Dennis
