### ISSUE TITLE
init script is incompatible with chkconfig

### ISSUE THREAD

**Issue by deorus** [puppet-community/puppet-kafka#5]
This was run on a RHEL 6 machine.
The init file is not compatible with chkconfig:

> Error: Could not enable kafka: Execution of '/sbin/chkconfig --add kafka' returned 1: service kafka does not support chkconfig
> Error: /Stage[main]/Kafka::Broker::Service/Service[kafka]/ensure: change from stopped to running failed: Could not enable kafka: Execution of '/sbin/chkconfig --add kafka' returned 1: service kafka does not support chkconfig

**Comment by TristanPeers** [comment]
Same issue above confirmed on Centos 6.5 x64:

Error: Could not enable kafka: Execution of '/sbin/chkconfig --add kafka' returned 1: service kafka does not support chkconfig
Error: /Stage[main]/Kafka::Broker::Service/Service[kafka]/ensure: change from stopped to running failed: Could not enable kafka: Execution of '/sbin/chkconfig --add kafka' returned 1: service kafka does not support chkconfig

Adding chkconfig init settings as per @deorus fixed it for me also.

**Comment by TristanPeers** [comment]
Just to update my last comment. It seems a commit was made on Mar 30th which contains the fix above. See last file here:

https://github.com/puppet-community/puppet-kafka/commit/1a165a0adfc5753f7e7086f11b9dc31004c1cea8

Unfortunately the last release (1.01) was on Mar 24th so this does not contain the fix therefore if you are using Puppet forge you will not get the changes above.

**Comment by dhoppe** [comment]
Hello Alex, 

thank you very much for your contribution. This issue has been resolved by commit https://github.com/puppet-community/puppet-kafka/commit/389fd55d0e75b23e00aa4915babfb74a4bc5508a.

Kind regards,
Dennis
